site_name: College Hive
site_author: Sanjay Bandaru

site_description: >-
  College Hive is a platform for students to share their knowledge and experiences with other students. 
  It is a platform for students to learn from each other and grow together.

theme:
  name: material

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


# nav:
#   - Home: index.md
#   - Course Subjects: Table of Content.md
#   - French:
#       - Subpage1: French/numbers.md
#       - Subpage2: directory1/subpage2.md
#   - Directory2:
#       - Subpage3: directory2/subpage3.md
#       - Subpage4: directory2/subpage4.md

# nav:
#     - Home: 'index.md'
#     - 'User Guide':
#         - 'Writing your docs': 'writing-your-docs.md'
#         - 'Styling your docs': 'styling-your-docs.md'
#     - About:
#         - 'License': 'license.md'
#         - 'Release Notes': 'release-notes.md'

markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  analytics:
    provider: google
    property: G-M16XXN4ERH
  social:
    - icon: fontawesome/brands/linkedin  
      link: https://www.linkedin.com/company/college-hives/
  generator: false    

extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'

copyright: Copyright &copy; 2023 Sanjay Bandaru
